/**
 * prvctice UI Kit — Pre-built component library for sandboxed iframe apps.
 *
 * Exports CSS (fonts + foundation + layout + components + interactive + media)
 * and JS (helpers + runtime) as cached strings for injection into every iframe
 * via sandbox.ts buildSrcdoc().
 *
 * Font files are pre-encoded as base64 data URIs in fonts.css (generated by
 * scripts/generate-uikit-fonts.js). All imports use Vite's ?raw suffix so
 * the entire UI Kit is available synchronously — no async init needed.
 */

// CSS imports (Vite inlines as raw strings at build time)
import fontsCSS from './css/fonts.css?raw';
import foundationCSS from './css/foundation.css?raw';
import layoutCSS from './css/layout.css?raw';
import componentsCSS from './css/components.css?raw';
import interactiveCSS from './css/interactive.css?raw';
import mediaCSS from './css/media.css?raw';
import chartsCSS from './css/charts.css?raw';

// JS imports (Vite inlines as raw strings at build time)
import helpersJS from './js/helpers.js?raw';
import runtimeJS from './js/runtime.js?raw';
import chartsJS from './js/charts.js?raw';
import audioJS from './js/audio.js?raw';
import notificationsJS from './js/notifications.js?raw';
import animationJS from './js/animation.js?raw';
import streamingJS from './js/streaming.js?raw';
import formsJS from './js/forms.js?raw';
import navigationJS from './js/navigation.js?raw';
import mediaPlaybackJS from './js/media-playback.js?raw';
import mathJS from './js/math.js?raw';
import transportJS from './js/transport.js?raw';
import midiRecorderJS from './js/midi-recorder.js?raw';
import knobJS from './js/knob.js?raw';
import faderJS from './js/fader.js?raw';
import trackManagerJS from './js/track-manager.js?raw';
import audioBufferJS from './js/audio-buffer.js?raw';
import imageJS from './js/image.js?raw';
import frameCaptureJS from './js/frame-capture.js?raw';
import timelineJS from './js/timeline.js?raw';

// ---------------------------------------------------------------------------
// CSS concatenation
// ---------------------------------------------------------------------------

function minifyCSS(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '') // strip comments
    .replace(/\s*\n\s*/g, ' ') // collapse newlines
    .replace(/\s*{\s*/g, '{') // trim around braces
    .replace(/\s*}\s*/g, '}')
    .replace(/\s*;\s*/g, ';')
    .replace(/\s*:\s*/g, ':')
    .replace(/\s*,\s*/g, ',')
    .trim();
}

let _cssCache: string | null = null;
let _jsCache: string | null = null;

/**
 * Get the complete UI Kit CSS (fonts + foundation + layout + components +
 * interactive + media) as a single minified string.
 *
 * The result is cached after the first call.
 */
export function getUIKitCSS(): string {
  if (_cssCache !== null) return _cssCache;

  const layerCSS = [
    foundationCSS,
    layoutCSS,
    componentsCSS,
    interactiveCSS,
    mediaCSS,
    chartsCSS,
  ].join('\n');

  // Fonts CSS contains base64 data URIs — don't minify (the encoded data
  // contains characters like colons and semicolons that the naive minifier
  // would break). Only minify the layer CSS.
  _cssCache = fontsCSS + '\n' + minifyCSS(layerCSS);
  return _cssCache;
}

/**
 * Get the complete UI Kit JS (helpers + runtime) as a single string.
 *
 * The result is cached after the first call.
 */
export function getUIKitJS(): string {
  if (_jsCache !== null) return _jsCache;
  _jsCache =
    helpersJS +
    '\n' +
    runtimeJS +
    '\n' +
    chartsJS +
    '\n' +
    audioJS +
    '\n' +
    audioBufferJS +
    '\n' +
    notificationsJS +
    '\n' +
    animationJS +
    '\n' +
    streamingJS +
    '\n' +
    formsJS +
    '\n' +
    navigationJS +
    '\n' +
    mediaPlaybackJS +
    '\n' +
    mathJS +
    '\n' +
    transportJS +
    '\n' +
    midiRecorderJS +
    '\n' +
    knobJS +
    '\n' +
    faderJS +
    '\n' +
    trackManagerJS +
    '\n' +
    imageJS +
    '\n' +
    frameCaptureJS +
    '\n' +
    timelineJS;
  return _jsCache;
}

// ---------------------------------------------------------------------------
// Cache invalidation (for tests / hot reload)
// ---------------------------------------------------------------------------

export function clearUIKitCache(): void {
  _cssCache = null;
  _jsCache = null;
}
