/**
 * SDK Surface Schema — Single source of truth for all prvctice.* methods.
 *
 * Every public method in the SDK is declared here. Downstream consumers
 * (appReviewer allowlist, available connectors list, API docs) derive their
 * data from this schema via helper exports at the bottom of this file.
 *
 * To add a new SDK method: add an entry here. That's it.
 */

// ---------------------------------------------------------------------------
// SDK Version — bump when the SDK surface changes
// ---------------------------------------------------------------------------

/** Semantic version of the SDK contract. Sent in bridge handshake. */
export const SDK_VERSION = '3.0.0';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type TransportMode =
  | 'local' // runs in iframe, no postMessage
  | 'bridge' // _request() round-trip
  | 'connector' // _request() with connector:request type
  | 'callback' // registers a callback, returns unsubscribe
  | 'fire-and-forget' // _send() without waiting
  | 'custom'; // special handling (e.g. download listener)

export interface SdkMethod {
  readonly namespace: string; // '' for top-level, 'storage', 'ai', etc.
  readonly method: string; // 'get', 'complete', etc.
  readonly params: string; // e.g. '(key: string)' — documentation only
  readonly returns: string; // e.g. 'Promise<any>' — documentation only
  readonly transport: TransportMode;
  readonly source: string; // 'bridgeSDK' | 'audio.js' | 'math.js' | etc.
  readonly since: string; // version when added: '1.0', '2.0', '2.1'
  readonly deprecated?: string; // version when deprecated
  readonly connector?: string; // backend connector ID if transport is 'connector'
}

export interface SdkConnector {
  readonly id: string; // 'weather', 'web-fetch', 'media-tools'
  readonly sdkNamespace: string; // 'weather', 'web', 'media'
  readonly requiresKey?: string; // key name: 'tmdb', 'youtube', 'discogs'
  readonly since: string;
}

// ---------------------------------------------------------------------------
// Method Registry
// ---------------------------------------------------------------------------

export const SDK_METHODS: readonly SdkMethod[] = [
  // ── Top-level ──
  {
    namespace: '',
    method: 'onReady',
    params: '(cb: Function)',
    returns: 'void',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '1.0',
  },
  {
    namespace: '',
    method: 'onDispose',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: '',
    method: 'openUrl',
    params: '(url: string)',
    returns: 'void',
    transport: 'fire-and-forget',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: '',
    method: 'enrich',
    params: '(data: any, question: string, options?: object)',
    returns: 'Promise<any>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.1',
  },
  {
    namespace: '',
    method: 'animate',
    params: '(selector: string, props: object, opts?: object)',
    returns: '{ cancel: () => void, finished: Promise<void> }',
    transport: 'local',
    source: 'animation.js',
    since: '2.1',
  },
  {
    namespace: '',
    method: 'sequence',
    params: '(steps: Array)',
    returns: 'Promise<void>',
    transport: 'local',
    source: 'animation.js',
    since: '2.1',
  },
  {
    namespace: '',
    method: 'animateValue',
    params: '(target: Element, from: number, to: number, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'animation.js',
    since: '2.1',
  },
  {
    namespace: '',
    method: 'load',
    params: '(modules: string[])',
    returns: 'Promise<void>',
    transport: 'local',
    source: 'runtime.js',
    since: '3.0',
  },

  // ── Storage ──
  {
    namespace: 'storage',
    method: 'get',
    params: '(key: string)',
    returns: 'Promise<any>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '1.0',
  },
  {
    namespace: 'storage',
    method: 'set',
    params: '(key: string, value: any)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '1.0',
  },
  {
    namespace: 'storage',
    method: 'delete',
    params: '(key: string)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '1.0',
  },
  {
    namespace: 'storage',
    method: 'usage',
    params: '()',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.1',
  },

  // ── Theme ──
  {
    namespace: 'theme',
    method: 'get',
    params: '()',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '1.0',
  },
  {
    namespace: 'theme',
    method: 'onChange',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '1.0',
  },

  // ── Time ──
  {
    namespace: 'time',
    method: 'now',
    params: '()',
    returns: 'string',
    transport: 'local',
    source: 'bridgeSDK',
    since: '1.0',
  },
  {
    namespace: 'time',
    method: 'timezone',
    params: '()',
    returns: 'string',
    transport: 'local',
    source: 'bridgeSDK',
    since: '1.0',
  },

  // ── Location ──
  {
    namespace: 'location',
    method: 'current',
    params: '()',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'location',
  },
  {
    namespace: 'location',
    method: 'geocode',
    params: '(name: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'geocoding',
  },
  {
    namespace: 'location',
    method: 'reverseGeocode',
    params: '(lat: number, lon: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'geocoding',
  },

  // ── Window ──
  {
    namespace: 'window',
    method: 'setTitle',
    params: '(title: string)',
    returns: 'void',
    transport: 'fire-and-forget',
    source: 'bridgeSDK',
    since: '1.0',
  },
  {
    namespace: 'window',
    method: 'resize',
    params: '(w: number, h: number)',
    returns: 'void',
    transport: 'fire-and-forget',
    source: 'bridgeSDK',
    since: '1.0',
  },
  {
    namespace: 'window',
    method: 'onFocus',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '1.0',
  },
  {
    namespace: 'window',
    method: 'onClose',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '1.0',
  },

  // ── AI ──
  {
    namespace: 'ai',
    method: 'complete',
    params: '(prompt: string, options?: object)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'ai',
  },
  {
    namespace: 'ai',
    method: 'stream',
    params: '(prompt: string, opts?: object)',
    returns: 'object',
    transport: 'bridge',
    source: 'streaming.js',
    since: '2.1',
  },

  // ── Web ──
  {
    namespace: 'web',
    method: 'fetch',
    params: '(url: string, options?: object)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'web-fetch',
  },

  // ── Weather ──
  {
    namespace: 'weather',
    method: 'current',
    params: '(location?: any)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'weather',
  },
  {
    namespace: 'weather',
    method: 'forecast',
    params: '(location?: any, days?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'weather',
  },

  // ── News ──
  {
    namespace: 'news',
    method: 'fetch',
    params: '(feedUrl: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'news',
  },
  {
    namespace: 'news',
    method: 'search',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'news',
  },
  {
    namespace: 'news',
    method: 'headlines',
    params: '(topic?: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'news',
  },

  // ── Wikipedia ──
  {
    namespace: 'wikipedia',
    method: 'search',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'wikipedia',
  },
  {
    namespace: 'wikipedia',
    method: 'images',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'wikipedia',
  },

  // ── Books ──
  {
    namespace: 'books',
    method: 'search',
    params: '(query: string, limit?: number, author?: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'books',
  },

  // ── Academic ──
  {
    namespace: 'academic',
    method: 'search',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'academic',
  },

  // ── Movies ──
  {
    namespace: 'movies',
    method: 'search',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'movies',
  },
  {
    namespace: 'movies',
    method: 'trending',
    params: '(mediaType?: string, timeWindow?: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'movies',
  },

  // ── Music ──
  {
    namespace: 'music',
    method: 'search',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'music',
  },

  // ── YouTube ──
  {
    namespace: 'youtube',
    method: 'search',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'youtube',
  },

  // ── Art ──
  {
    namespace: 'art',
    method: 'search',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'art',
  },
  {
    namespace: 'art',
    method: 'searchArtInstitute',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'art',
  },
  {
    namespace: 'art',
    method: 'searchMetMuseum',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'art',
  },

  // ── Sports ──
  {
    namespace: 'sports',
    method: 'scores',
    params: '(sportOrOpts: any, league?: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'sports',
  },
  {
    namespace: 'sports',
    method: 'standings',
    params: '(sportOrOpts: any, league?: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'sports',
  },
  {
    namespace: 'sports',
    method: 'schedule',
    params: '(sportOrOpts: any, league?: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'sports',
  },

  // ── Markets ──
  {
    namespace: 'markets',
    method: 'crypto',
    params: '(ids?: string, vs?: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'markets',
  },
  {
    namespace: 'markets',
    method: 'stock',
    params: '(symbol: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'markets',
  },
  {
    namespace: 'markets',
    method: 'trending',
    params: '()',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'markets',
  },

  // ── Europeana ──
  {
    namespace: 'europeana',
    method: 'search',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'europeana',
  },

  // ── Smithsonian ──
  {
    namespace: 'smithsonian',
    method: 'search',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'smithsonian',
  },

  // ── Library of Congress ──
  {
    namespace: 'loc',
    method: 'search',
    params: '(query: string, limit?: number)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'loc',
  },

  // ── Google Books ──
  {
    namespace: 'googleBooks',
    method: 'search',
    params: '(query: string, limit?: number, author?: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'google-books',
  },

  // ── Films ──
  {
    namespace: 'films',
    method: 'search',
    params: '(options?: object)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'films',
  },

  // ── Vision ──
  {
    namespace: 'vision',
    method: 'describe',
    params: '(imageData: string, prompt?: string, provider?: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'vision',
  },

  // ── Media Tools (server-side processing) ──
  {
    namespace: 'media',
    method: 'probe',
    params: '(opts: object)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'media-tools',
  },
  {
    namespace: 'media',
    method: 'convert',
    params: '(opts: object)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'media-tools',
  },
  {
    namespace: 'media',
    method: 'extractAudio',
    params: '(opts: object)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'media-tools',
  },
  {
    namespace: 'media',
    method: 'screenshot',
    params: '(opts: object)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'media-tools',
  },
  {
    namespace: 'media',
    method: 'trim',
    params: '(opts: object)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.1',
    connector: 'media-tools',
  },

  // ── Media ──
  {
    namespace: 'media',
    method: 'startMicrophone',
    params: '(opts?: object)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: 'media',
    method: 'stopMicrophone',
    params: '()',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: 'media',
    method: 'onAudioData',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: 'media',
    method: 'playAudio',
    params: '(url: string)',
    returns: 'object',
    transport: 'bridge',
    source: 'media-playback.js',
    since: '2.1',
  },
  {
    namespace: 'media',
    method: 'loadImage',
    params: '(url: string)',
    returns: 'Promise<{ dataUri: string, width: number, height: number }>',
    transport: 'bridge',
    source: 'media-playback.js',
    since: '2.1',
  },
  {
    namespace: 'media',
    method: 'download',
    params: '(base64: string, filename: string, mimeType?: string)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.0',
  },

  // ── Camera ──
  {
    namespace: 'camera',
    method: 'start',
    params: '(opts?: object)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'camera',
    method: 'capture',
    params: '()',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'camera',
    method: 'stop',
    params: '()',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'camera',
    method: 'onFrame',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.3',
  },

  // ── Video ──
  {
    namespace: 'video',
    method: 'load',
    params: '(opts: object)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'video',
    method: 'play',
    params: '(playerId: string, startTime?: number)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'video',
    method: 'pause',
    params: '(playerId: string)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'video',
    method: 'seek',
    params: '(playerId: string, time: number)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'video',
    method: 'seekAndCapture',
    params: '(playerId: string, time: number, width?: number, height?: number)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'video',
    method: 'unload',
    params: '(playerId: string)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },

  // ── GIF ──
  {
    namespace: 'gif',
    method: 'create',
    params: '(opts?: object)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'gif',
    method: 'addFrame',
    params: '(encoderId: string, dataUri: string, delay?: number)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'gif',
    method: 'finish',
    params: '(encoderId: string)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'gif',
    method: 'cancel',
    params: '(encoderId: string)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.3',
  },
  {
    namespace: 'gif',
    method: 'onProgress',
    params: '(encoderId: string, cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.3',
  },

  // ── Audio ──
  {
    namespace: 'audio',
    method: 'tone',
    params: '(opts: object)',
    returns: 'void',
    transport: 'local',
    source: 'audio.js',
    since: '1.2',
  },
  {
    namespace: 'audio',
    method: 'sequence',
    params: '(notes: Array, opts?: object)',
    returns: 'void',
    transport: 'local',
    source: 'audio.js',
    since: '1.2',
  },
  {
    namespace: 'audio',
    method: 'createContext',
    params: '()',
    returns: 'AudioContext',
    transport: 'local',
    source: 'audio.js',
    since: '1.2',
  },
  {
    namespace: 'audio',
    method: 'createAnalyser',
    params: '(opts?: object)',
    returns: 'AnalyserNode',
    transport: 'local',
    source: 'audio.js',
    since: '1.2',
  },
  {
    namespace: 'audio',
    method: 'getMasterGain',
    params: '()',
    returns: 'GainNode',
    transport: 'local',
    source: 'audio.js',
    since: '2.0',
  },
  {
    namespace: 'audio',
    method: 'getAnalyser',
    params: '()',
    returns: 'AnalyserNode',
    transport: 'local',
    source: 'audio.js',
    since: '2.0',
  },
  {
    namespace: 'audio',
    method: 'createRecorder',
    params: '(opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'audio.js',
    since: '2.0',
  },
  {
    namespace: 'audio',
    method: 'renderOffline',
    params: '(fn: Function, duration: number, sampleRate?: number)',
    returns: 'Promise<AudioBuffer>',
    transport: 'local',
    source: 'audio.js',
    since: '2.0',
  },
  {
    namespace: 'audio',
    method: 'encodeWAV',
    params: '(buffer: AudioBuffer)',
    returns: 'Blob',
    transport: 'local',
    source: 'audio.js',
    since: '2.0',
  },
  {
    namespace: 'audio',
    method: 'bufferToBase64',
    params: '(buffer: AudioBuffer)',
    returns: 'string',
    transport: 'local',
    source: 'audio.js',
    since: '2.0',
  },
  {
    namespace: 'audio',
    method: 'createTransport',
    params: '(opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'transport.js',
    since: '2.2',
  },
  {
    namespace: 'audio',
    method: 'createMidiRecorder',
    params: '(opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'midi-recorder.js',
    since: '2.2',
  },
  {
    namespace: 'audio',
    method: 'createTrackManager',
    params: '(opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'track-manager.js',
    since: '2.2',
  },

  // ── Audio Buffer ──
  {
    namespace: 'audio.buffer',
    method: 'decode',
    params: '(arrayBuffer: ArrayBuffer)',
    returns: 'Promise<AudioBuffer>',
    transport: 'local',
    source: 'audio-buffer.js',
    since: '3.0',
  },
  {
    namespace: 'audio.buffer',
    method: 'slice',
    params: '(buffer: AudioBuffer, startTime: number, endTime: number)',
    returns: 'AudioBuffer',
    transport: 'local',
    source: 'audio-buffer.js',
    since: '3.0',
  },
  {
    namespace: 'audio.buffer',
    method: 'reverse',
    params: '(buffer: AudioBuffer)',
    returns: 'AudioBuffer',
    transport: 'local',
    source: 'audio-buffer.js',
    since: '3.0',
  },
  {
    namespace: 'audio.buffer',
    method: 'normalize',
    params: '(buffer: AudioBuffer)',
    returns: 'AudioBuffer',
    transport: 'local',
    source: 'audio-buffer.js',
    since: '3.0',
  },
  {
    namespace: 'audio.buffer',
    method: 'fade',
    params: '(buffer: AudioBuffer, type: string, duration: number)',
    returns: 'AudioBuffer',
    transport: 'local',
    source: 'audio-buffer.js',
    since: '3.0',
  },
  {
    namespace: 'audio.buffer',
    method: 'mix',
    params: '(bufferA: AudioBuffer, bufferB: AudioBuffer, opts?: object)',
    returns: 'AudioBuffer',
    transport: 'local',
    source: 'audio-buffer.js',
    since: '3.0',
  },
  {
    namespace: 'audio.buffer',
    method: 'pitchShift',
    params: '(buffer: AudioBuffer, semitones: number)',
    returns: 'Promise<AudioBuffer>',
    transport: 'local',
    source: 'audio-buffer.js',
    since: '3.0',
  },
  {
    namespace: 'audio.buffer',
    method: 'waveformPeaks',
    params: '(buffer: AudioBuffer, resolution?: number)',
    returns: 'Array<object>',
    transport: 'local',
    source: 'audio-buffer.js',
    since: '3.0',
  },

  // ── Image Processing ──
  {
    namespace: 'image',
    method: 'grayscale',
    params: '(canvas: HTMLCanvasElement)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'sepia',
    params: '(canvas: HTMLCanvasElement)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'invert',
    params: '(canvas: HTMLCanvasElement)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'blur',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'sharpen',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'brightness',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'contrast',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'saturation',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'hueRotate',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'vignette',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'noise',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'posterize',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'emboss',
    params: '(canvas: HTMLCanvasElement)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'pipeline',
    params: '(source: HTMLCanvasElement, steps: Array<object>)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'crop',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'resize',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'rotate',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'flip',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'composite',
    params: '(base: HTMLCanvasElement, overlay: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'text',
    params: '(canvas: HTMLCanvasElement, text: string, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'exportImage',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'string',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },
  {
    namespace: 'image',
    method: 'exportBlob',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'Promise<Blob>',
    transport: 'local',
    source: 'image.js',
    since: '3.0',
  },

  // ── Frame Capture ──
  {
    namespace: 'capture',
    method: 'start',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'frame-capture.js',
    since: '3.0',
  },
  {
    namespace: 'capture',
    method: 'snapshot',
    params: '(canvas: HTMLCanvasElement, opts?: object)',
    returns: 'HTMLCanvasElement',
    transport: 'local',
    source: 'frame-capture.js',
    since: '3.0',
  },

  // ── Format ──
  {
    namespace: 'format',
    method: 'number',
    params: '(n: number)',
    returns: 'string',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },
  {
    namespace: 'format',
    method: 'percent',
    params: '(n: number)',
    returns: 'string',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },
  {
    namespace: 'format',
    method: 'currency',
    params: '(n: number)',
    returns: 'string',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },
  {
    namespace: 'format',
    method: 'relativeTime',
    params: '(date: Date|string)',
    returns: 'string',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },

  // ── Math ──
  {
    namespace: 'math',
    method: 'evaluate',
    params: '(expr: string)',
    returns: 'number',
    transport: 'local',
    source: 'math.js',
    since: '2.1',
  },

  // ── Skills ──
  {
    namespace: 'skills',
    method: 'list',
    params: '()',
    returns: 'Promise<Array>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'skills',
  },
  {
    namespace: 'skills',
    method: 'execute',
    params: '(skillId: string, input?: any)',
    returns: 'Promise<any>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'skills',
  },

  // ── Calendar ──
  {
    namespace: 'calendar',
    method: 'parse',
    params: '(content: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'calendar',
  },

  // ── Clipboard ──
  {
    namespace: 'clipboard',
    method: 'readText',
    params: '()',
    returns: 'Promise<string>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'clipboard',
  },
  {
    namespace: 'clipboard',
    method: 'writeText',
    params: '(text: string)',
    returns: 'Promise<void>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'clipboard',
  },

  // ── Files ──
  {
    namespace: 'files',
    method: 'read',
    params: '(path: string)',
    returns: 'Promise<string>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'files',
  },
  {
    namespace: 'files',
    method: 'list',
    params: '(directory?: string)',
    returns: 'Promise<Array>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '1.0',
    connector: 'files',
  },

  // ── VFS ──
  {
    namespace: 'fs',
    method: 'read',
    params: '(path: string)',
    returns: 'Promise<any>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'vfs',
  },
  {
    namespace: 'fs',
    method: 'list',
    params: '(path?: string)',
    returns: 'Promise<Array>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'vfs',
  },
  {
    namespace: 'fs',
    method: 'stat',
    params: '(path: string)',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'vfs',
  },
  {
    namespace: 'fs',
    method: 'listBlobs',
    params: '(accept?: string)',
    returns: 'Promise<Array>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '3.0',
    connector: 'vfs',
  },
  {
    namespace: 'fs',
    method: 'readAsDataUrl',
    params: '(path: string)',
    returns: 'Promise<string>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '3.0',
    connector: 'vfs',
  },

  // ── Actions ──
  {
    namespace: 'actions',
    method: 'register',
    params: '(id: string, handler: Function)',
    returns: 'void',
    transport: 'local',
    source: 'bridgeSDK',
    since: '1.0',
  },
  {
    namespace: 'actions',
    method: 'unregister',
    params: '(id: string)',
    returns: 'void',
    transport: 'local',
    source: 'bridgeSDK',
    since: '1.0',
  },

  // ── Chat ──
  {
    namespace: 'chat',
    method: 'getMessages',
    params: '(opts?: object)',
    returns: 'Promise<Array>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'chat',
  },
  {
    namespace: 'chat',
    method: 'getConversation',
    params: '()',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'chat',
  },
  {
    namespace: 'chat',
    method: 'sendMessage',
    params: '(text: string)',
    returns: 'Promise<void>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'chat',
  },
  {
    namespace: 'chat',
    method: 'onMessage',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: 'chat',
    method: 'onStreamingUpdate',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: 'chat',
    method: 'onConversationChanged',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },

  // ── Context ──
  {
    namespace: 'context',
    method: 'getOpenApps',
    params: '()',
    returns: 'Promise<Array>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'context',
  },
  {
    namespace: 'context',
    method: 'getActiveApp',
    params: '()',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'context',
  },
  {
    namespace: 'context',
    method: 'getWorkspace',
    params: '()',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'context',
  },
  {
    namespace: 'context',
    method: 'getUser',
    params: '()',
    returns: 'Promise<object>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'context',
  },
  {
    namespace: 'context',
    method: 'onAppOpened',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: 'context',
    method: 'onAppClosed',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },

  // ── Connectors ──
  {
    namespace: 'connectors',
    method: 'check',
    params: '(connectorId?: string)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.0',
  },

  // ── Broadcast ──
  {
    namespace: 'broadcast',
    method: 'publish',
    params: '(channel: string, data: any)',
    returns: 'Promise<void>',
    transport: 'connector',
    source: 'bridgeSDK',
    since: '2.0',
    connector: 'broadcast',
  },
  {
    namespace: 'broadcast',
    method: 'subscribe',
    params: '(channel: string, cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: 'broadcast',
    method: 'unsubscribe',
    params: '(channel: string)',
    returns: 'void',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '2.0',
  },

  // ── Input ──
  {
    namespace: 'input',
    method: 'onMove',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: 'input',
    method: 'onKeyDown',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },
  {
    namespace: 'input',
    method: 'onKeyUp',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '2.0',
  },

  // ── Refresh ──
  {
    namespace: 'refresh',
    method: 'start',
    params: '(intervalMs?: number)',
    returns: 'void',
    transport: 'fire-and-forget',
    source: 'bridgeSDK',
    since: '1.2',
  },
  {
    namespace: 'refresh',
    method: 'stop',
    params: '()',
    returns: 'void',
    transport: 'fire-and-forget',
    source: 'bridgeSDK',
    since: '1.2',
  },
  {
    namespace: 'refresh',
    method: 'requestNow',
    params: '()',
    returns: 'void',
    transport: 'fire-and-forget',
    source: 'bridgeSDK',
    since: '1.2',
  },
  {
    namespace: 'refresh',
    method: 'onRefresh',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '1.2',
  },

  // ── UI: Notifications ──
  {
    namespace: 'ui',
    method: 'toast',
    params: '(opts: object)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'notifications.js',
    since: '2.1',
  },
  {
    namespace: 'ui',
    method: 'confirm',
    params: '(opts: object)',
    returns: 'Promise<boolean>',
    transport: 'bridge',
    source: 'notifications.js',
    since: '2.1',
  },
  {
    namespace: 'ui',
    method: 'alert',
    params: '(opts: object)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'notifications.js',
    since: '2.1',
  },

  // ── UI: Forms ──
  {
    namespace: 'ui',
    method: 'form',
    params: '(container: Element, opts: object)',
    returns: 'object',
    transport: 'local',
    source: 'forms.js',
    since: '2.1',
  },

  // ── UI: Navigation ──
  {
    namespace: 'ui',
    method: 'router',
    params: '(opts: object)',
    returns: 'object',
    transport: 'local',
    source: 'navigation.js',
    since: '2.1',
  },

  // ── UI: Components (runtime.js) ──
  {
    namespace: 'ui',
    method: 'clock',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'analogClock',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'timer',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'stepper',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'tabs',
    params: '(container: Element, opts: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'canvas',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'dropzone',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'waveform',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'mediaPlayer',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'audioRecorder',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'dataView',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'base64ToBlob',
    params: '(b64: string, mime?: string)',
    returns: 'Blob',
    transport: 'local',
    source: 'runtime.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'errorState',
    params: '(container: Element, opts?: object)',
    returns: 'void',
    transport: 'local',
    source: 'runtime.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'emptyState',
    params: '(container: Element, opts?: object)',
    returns: 'void',
    transport: 'local',
    source: 'runtime.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'staleBadge',
    params: '(container: Element, opts?: object)',
    returns: 'void',
    transport: 'local',
    source: 'runtime.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'animateEntrance',
    params: '(el: Element)',
    returns: '{ dispose: () => void }',
    transport: 'local',
    source: 'runtime.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'animateValue',
    params: '(container: Element, from: number, to: number, opts?: object)',
    returns: '{ dispose: () => void }',
    transport: 'local',
    source: 'runtime.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'filePicker',
    params: '(opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'runtime.js',
    since: '3.0',
  },

  // ── UI: Charts ──
  {
    namespace: 'ui',
    method: 'sparkline',
    params: '(container: Element, opts: object)',
    returns: 'object',
    transport: 'local',
    source: 'charts.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'barChart',
    params: '(container: Element, opts: object)',
    returns: 'object',
    transport: 'local',
    source: 'charts.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'lineChart',
    params: '(container: Element, opts: object)',
    returns: 'object',
    transport: 'local',
    source: 'charts.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'gauge',
    params: '(container: Element, opts: object)',
    returns: 'object',
    transport: 'local',
    source: 'charts.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'pieChart',
    params: '(container: Element, opts: object)',
    returns: 'object',
    transport: 'local',
    source: 'charts.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'progressRing',
    params: '(container: Element, opts: object)',
    returns: 'object',
    transport: 'local',
    source: 'charts.js',
    since: '1.2',
  },

  // ── UI: Audio visualizers ──
  {
    namespace: 'ui',
    method: 'oscilloscope',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'audio.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'spectrogram',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'audio.js',
    since: '1.2',
  },
  {
    namespace: 'ui',
    method: 'piano',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'audio.js',
    since: '2.0',
  },
  {
    namespace: 'ui',
    method: 'pads',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'audio.js',
    since: '2.0',
  },

  // ── UI: Knob ──
  {
    namespace: 'ui',
    method: 'knob',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'knob.js',
    since: '2.2',
  },

  // ── UI: Fader ──
  {
    namespace: 'ui',
    method: 'fader',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'fader.js',
    since: '3.0',
  },

  // ── UI: Timeline ──
  {
    namespace: 'ui',
    method: 'timeline',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'timeline.js',
    since: '3.0',
  },

  // ── UI: Spectrum ──
  {
    namespace: 'ui',
    method: 'spectrum',
    params: '(container: Element, opts?: object)',
    returns: 'object',
    transport: 'local',
    source: 'audio.js',
    since: '3.0',
  },

  // ── Mixer (host audio engine bridge) ──
  {
    namespace: 'mixer',
    method: 'connect',
    params: '(opts?: object)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'disconnect',
    params: '()',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'onDisconnected',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'noteOn',
    params: '(freq: number, opts?: object)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'noteOff',
    params: '(voiceId: string)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setVoiceFrequency',
    params: '(voiceId: string, freq: number, rampTime?: number)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setVoiceGain',
    params: '(voiceId: string, gain: number, rampTime?: number)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'tone',
    params: '(freq: number, duration: number, opts?: object)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'synthDrumVoice',
    params: '(voice: string, velocity: number)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'allNotesOff',
    params: '()',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setGain',
    params: '(channelId: string, value: number)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setPan',
    params: '(channelId: string, value: number)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setMute',
    params: '(channelId: string, value: boolean)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setSolo',
    params: '(channelId: string, value: boolean)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setReverbSend',
    params: '(channelId: string, value: number)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setRecordArm',
    params: '(channelId: string, value: boolean)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setMasterGain',
    params: '(value: number)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setMasterMute',
    params: '(value: boolean)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setBpm',
    params: '(value: number)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'setMetronome',
    params: '(enabled: boolean)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'transportPlay',
    params: '()',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'transportStop',
    params: '()',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'getState',
    params: '()',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'subscribeState',
    params: '()',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'onStateChange',
    params: '(cb: Function)',
    returns: 'Function',
    transport: 'callback',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'getAnalyserData',
    params: '(channelId?: string)',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'startRecording',
    params: '()',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'stopRecording',
    params: '()',
    returns: 'Promise<object>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'playRecording',
    params: '()',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'pauseRecording',
    params: '()',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'stopPlayback',
    params: '()',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'seekRecording',
    params: '(time: number)',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
  {
    namespace: 'mixer',
    method: 'clearRecording',
    params: '()',
    returns: 'Promise<void>',
    transport: 'bridge',
    source: 'bridgeSDK',
    since: '3.0',
  },
] as const;

// ---------------------------------------------------------------------------
// Connector Registry
// ---------------------------------------------------------------------------

export const SDK_CONNECTORS: readonly SdkConnector[] = [
  { id: 'weather', sdkNamespace: 'weather', since: '1.0' },
  { id: 'news', sdkNamespace: 'news', since: '1.0' },
  { id: 'web-fetch', sdkNamespace: 'web', since: '1.0' },
  { id: 'ai', sdkNamespace: 'ai', since: '1.0' },
  { id: 'location', sdkNamespace: 'location', since: '1.0' },
  { id: 'storage', sdkNamespace: 'storage', since: '1.0' },
  { id: 'skills', sdkNamespace: 'skills', since: '1.0' },
  { id: 'calendar', sdkNamespace: 'calendar', since: '1.0' },
  { id: 'wikipedia', sdkNamespace: 'wikipedia', since: '1.0' },
  { id: 'books', sdkNamespace: 'books', since: '1.0' },
  { id: 'academic', sdkNamespace: 'academic', since: '1.0' },
  { id: 'art', sdkNamespace: 'art', since: '1.0' },
  { id: 'sports', sdkNamespace: 'sports', since: '1.0' },
  { id: 'movies', sdkNamespace: 'movies', since: '1.0', requiresKey: 'tmdb' },
  { id: 'music', sdkNamespace: 'music', since: '1.0', requiresKey: 'discogs' },
  { id: 'youtube', sdkNamespace: 'youtube', since: '1.0', requiresKey: 'youtube' },
  { id: 'markets', sdkNamespace: 'markets', since: '2.0' },
  { id: 'europeana', sdkNamespace: 'europeana', since: '2.1' },
  { id: 'smithsonian', sdkNamespace: 'smithsonian', since: '2.1', requiresKey: 'smithsonian' },
  { id: 'loc', sdkNamespace: 'loc', since: '2.1' },
  { id: 'google-books', sdkNamespace: 'googleBooks', since: '2.1' },
  { id: 'films', sdkNamespace: 'films', since: '2.1', requiresKey: 'tmdb' },
  { id: 'vision', sdkNamespace: 'vision', since: '2.1' },
  { id: 'media-tools', sdkNamespace: 'media', since: '2.1' },
  { id: 'geocoding', sdkNamespace: 'location', since: '2.1' },
  { id: 'clipboard', sdkNamespace: 'clipboard', since: '1.0' },
  { id: 'files', sdkNamespace: 'files', since: '1.0' },
  { id: 'vfs', sdkNamespace: 'fs', since: '2.0' },
  { id: 'chat', sdkNamespace: 'chat', since: '2.0' },
  { id: 'context', sdkNamespace: 'context', since: '2.0' },
  { id: 'broadcast', sdkNamespace: 'broadcast', since: '2.0' },
];

// ---------------------------------------------------------------------------
// Derived Helpers — importable by appReviewer and useAppGenerator
// ---------------------------------------------------------------------------

/**
 * Full method path: 'prvctice.namespace.method' or 'prvctice.method' for top-level.
 */
function methodPath(m: SdkMethod): string {
  return m.namespace ? `prvctice.${m.namespace}.${m.method}` : `prvctice.${m.method}`;
}

/** All valid prvctice.* method paths as a Set (for appReviewer allowlist). */
let _validNamespacesCache: ReadonlySet<string> | null = null;
export function getValidNamespaces(): ReadonlySet<string> {
  if (_validNamespacesCache) return _validNamespacesCache;
  _validNamespacesCache = new Set(SDK_METHODS.map(methodPath));
  return _validNamespacesCache;
}

/** Connectors available without API keys (for useAppGenerator BASE_CONNECTORS). */
export function getBaseConnectors(): readonly string[] {
  return SDK_CONNECTORS.filter((c) => !c.requiresKey).map((c) => c.id);
}

/** Connectors requiring user-provided API keys (for useAppGenerator KEY_GATED_CONNECTORS). */
export function getKeyGatedConnectors(): ReadonlyArray<{
  readonly connector: string;
  readonly key: string;
}> {
  return SDK_CONNECTORS.filter((c) => c.requiresKey).map((c) => ({
    connector: c.id,
    key: c.requiresKey!,
  }));
}

/**
 * Map a hyphenated connector ID to its valid JS namespace name.
 * E.g., 'media-tools' -> 'media', 'google-books' -> 'googleBooks'.
 */
export function connectorSdkNamespace(connectorId: string): string {
  const entry = SDK_CONNECTORS.find((c) => c.id === connectorId);
  if (entry) return entry.sdkNamespace;
  // Fallback: camelCase the ID
  return connectorId.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
